# Site settings
title: david barsky, functioning programmer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://davidbarsky.com" # the base hostname & protocol for your site
twitter_username: thramp
github_username: davidbarsky

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
